// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News.Database;

#nullable disable

namespace News.Database.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220518211438_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticlesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ArticlesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TagArticles", (string)null);
                });

            modelBuilder.Entity("News.Database.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6300),
                            Text = "Now eldest new tastes plenty mother called misery get. Longer excuse for county nor except met its things. Narrow enough sex moment desire are. Hold who what come that seen read age its. Contained or estimable earnestly so perceived. Imprudence he in sufficient cultivated. Delighted promotion improving acuteness an newspaper offending he. Misery in am secure theirs giving an. Design on longer thrown oppose am.",
                            Title = "Article 1",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6300)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6302),
                            Text = "Carried nothing on am warrant towards. Polite in of in oh needed itself silent course. Assistance travelling so especially do prosperous appearance mr no celebrated. Wanted easily in my called formed suffer. Songs hoped sense as taken ye mirth at. Believe fat how six drawing pursuit minutes far. Same do seen head am part it dear open to. Whatever may scarcely judgment had.",
                            Title = "Article 2",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6302)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6303),
                            Text = "Society excited by cottage private an it esteems. Fully begin on by wound an. Girl rich in do up or both. At declared in as rejoiced of together. He impression collecting delightful unpleasant by prosperous as on. End too talent she object mrs wanted remove giving.",
                            Title = "Article 3",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6303)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6304),
                            Text = "Is post each that just leaf no. He connection interested so we an sympathize advantages. To said is it shed want do. Occasional middletons everything so to. Have spot part for his quit may. Enable it is square my an regard. Often merit stuff first oh up hills as he. Servants contempt as although addition dashwood is procured. Interest in yourself an do of numerous feelings cheerful confined.",
                            Title = "Article 4",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6304)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6305),
                            Text = "Is post each that just leaf no. He connection interested so we an sympathize advantages. To said is it shed want do. Occasional middletons everything so to. Have spot part for his quit may. Enable it is square my an regard. Often merit stuff first oh up hills as he. Servants contempt as although addition dashwood is procured. Interest in yourself an do of numerous feelings cheerful confined.",
                            Title = "Article 5",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6305)
                        });
                });

            modelBuilder.Entity("News.Database.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6295),
                            FirstName = "Rick",
                            LastName = "Sanchez",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6295)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6297),
                            FirstName = "Morty",
                            LastName = "Smith",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6297)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6297),
                            FirstName = "Miyamoto",
                            LastName = "Musashi",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6298)
                        });
                });

            modelBuilder.Entity("News.Database.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6278),
                            Name = "Business",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6279)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6283),
                            Name = "Technology",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6283)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6284),
                            Name = "Culture",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6284)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6285),
                            Name = "Health",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6285)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6286),
                            Name = "General News",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6286)
                        });
                });

            modelBuilder.Entity("News.Database.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6289),
                            Name = "breaking news",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6290)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6291),
                            Name = "war",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6292)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6292),
                            Name = "lmao",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6293)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6293),
                            Name = "sick",
                            UpdatedAt = new DateTime(2022, 5, 18, 21, 14, 37, 935, DateTimeKind.Utc).AddTicks(6293)
                        });
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("News.Database.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News.Database.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("News.Database.Entities.Article", b =>
                {
                    b.HasOne("News.Database.Entities.Author", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("News.Database.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("News.Database.Entities.Author", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("News.Database.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
